In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=666)

#### scikit-learn中的StandarScaler

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
standard_scalar = StandardScaler()
standard_scalar.fit(x_train)

StandardScaler()

In [8]:
standard_scalar.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [9]:
standard_scalar.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [10]:
x_train_standard = standard_scalar.transform(x_train)

In [11]:
x_test_standard = standard_scalar.transform(x_test)

#### 使用归一化后的数据进行 knn 分类

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train_standard, y_train)

KNeighborsClassifier(n_neighbors=3)

In [14]:
knn_clf.score(x_test_standard, y_test)

1.0

#### 使用自己封装的 StandardScaler

In [17]:
import sys
import os
sys.path.append(os.path.dirname(sys.path[0]))

In [19]:
from LibML.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_ratio=0.2, seed=666)

In [20]:
from LibML.preprocessing import StandardScaler

standard_scaler = StandardScaler
standard_scalar.fit(x_train)

StandardScaler()

In [21]:
standard_scalar.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [22]:
standard_scalar.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [23]:
x_train_standard = standard_scalar.transform(x_train)
x_test_standard = standard_scalar.transform(x_test)

In [26]:
from LibML.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(3)
knn_clf.fit(x_train_standard, y_train)

KNN(k=3)

In [27]:
y_predict = knn_clf.predict(x_test_standard)

In [28]:
from LibML.metrics import accuracy_score

In [29]:
accuracy_score(y_test, y_predict)

1.0